; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Fri Mar 16 2018 15:08:20 GMT+0000 (GMT Standard Time)
; Wait for set temperatures to be reached
M116 P0